name: test_build_and_deploy

on: [push]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          project_id: 'elad-playground'


      - name: check gcloud
        run: gcloud -v

      - name: maven build
        run: mvn install && mvn package

      - name: upload file
        shell: bash
        run: |
          mvn exec:java -Dexec.mainClass=com.doitintl.banias.BaniasPipeline \
          -Dexec.cleanupDaemonThreads=false \
          -Dexec.args=" \
          --project=elad-playground \
          --tempLocation=gs://autofleet_temp/ \
          --gcpTempLocation=gs://autofleet_temp/tmp \
          --stagingLocation=gs://autofleet_temp/pipeline-staging \
          --runner=DataflowRunner \
          --defaultWorkerLogLevel=DEBUG \
          --eventsSubscriptionPath=projects/elad-playground/subscriptions/AutoFleet_Subscription \
          --errorsTableName=error \
          --GCSSchemasBucketName=autofleet_schemas \
          --dataset=banias \
          --numWorkers=3 \
          "
